export const GET_DATAOFCRYPTOCURRENCY_REQUEST = 'GET_DATAOFCRYPTOCURRENCY_REQUEST';
export const GET_DATAOFCRYPTOCURRENCY_PASSED = 'GET_DATAOFCRYPTOCURRENCY_PASSED';
export const GET_DATAOFCRYPTOCURRENCY_FAILED = 'GET_DATAOFCRYPTOCURRENCY_FAILED';